pipeline {
   agent {
       docker {
           image "ruby"
       }
   }

   stages {
      stage('Build') {
         steps {
            echo 'Bulding or Roselve Dependencies!'
            sh 'bundle install'
         }
      }
      stage('Test') {
         steps {
            echo 'Runing regressions testes'
            sh 'bundle exec cucumber -p ci'
         }
      }
      stage('UAT') {
         steps {
            echo 'Wait for user acceptence'
            input(message: 'Go to production?', ok: 'Yes')
         }
      }
      stage('Prod') {
         steps {
            echo 'WebApp is Ready :)'
         }
      }
   }
}
